name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Toggle Workflow
        uses: StephenMP/workflow-toggle@v2.0.1
        with:
          token: ${{ secrets.MSEdgeRedirect_PAT }}
          workflow_id: winget-badge-update.yml
          action: disable
