name: Submit MSEdgeRedirect to winget

on:
  release:
    types: [published]

jobs:
  winget-bump:
    name: mser winget
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: Create winget PR
        run: |
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect_x86.exe'
          $asset64 = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect.exe'
          $version = $github.release.tag_name
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update -u "$asset64.browser_download_url|x64" "$asset.browser_download_url|x86" -v $version -t "${{ secrets.MSEdgeRedirect_PAT }}" -s rcmaehl.MSEdgeRedirect
