name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Specific tag name'
        required: true 
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: rcmaehl.MSEdgeRedirect
          version: ${{ inputs.tag_name || github.event.release.tag_name }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          delete-previous-version: 'true'
          token: ${{ secrets.MSEdgeRedirect_PAT }}
