name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: rcmaehl.MSEdgeRedirect
          version: ${{ github.event.release.tag_name }}
          delete-previous-version: 'true'
          token: ${{ secrets.MSEdgeRedirect_PAT }}
