name: Submit MSEdgeRedirect to winget

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Winget Release
        if: startsWith(github.ref, 'refs/tags/')
        run: | # rcmaehl.MSEdgeRedirect
            iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
            $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
            $installerUrl = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect.exe' | Select -ExpandProperty browser_download_url -First 1
            $github
            $installerUrl
            .\wingetcreate.exe update macley.testMSEdgeRedirecttest -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.RCMAEHL_PAT }}