name: Publish to WinGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: true 
        id: latesttag
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: rcmaehl.MSEdgeRedirect
          version: ${{ steps.latesttag.outputs.tag }}
          release-tag: ${{ steps.latesttag.outputs.tag }}
          delete-previous-version: 'true'
          token: ${{ secrets.MSEdgeRedirect_PAT }}
      - name: Toggle Workflow
        uses: StephenMP/workflow-toggle@v2.0.1
        with:
          token: ${{ secrets.MSEdgeRedirect_PAT }}
          workflow_id: winget-badge-update.yml
          action: enable
